Travis/fix manage tails
travisdesell/ngafid2.0 pull request #115
Opened 2023-09-11 17:27 UTC by travisdesell

2023-09-11 18:03 UTC, AarC10 requested changes

2023-09-12 18:10 UTC, travisdesell commented on src/main/java/org/ngafid/SendEmail.java
> +                    System.out.println("read password: '" + password + "'");
actually i should probably just remove these because we wouldn't want them printing to a log. will update.

2023-09-12 18:31 UTC, travisdesell commented on src/main/java/org/ngafid/SendEmail.java
> +                    System.out.println("read password: '" + password + "'");
okay just commented these out because we don't actually want to print them (had them in there for debugging why emails weren't getting sent out).

2023-09-12 18:32 UTC, travisdesell commented on src/main/java/org/ngafid/routes/GetCSV.java
> +            if (uploaderId == 284) {
we actually should have a no-email field in the user table of the database and pull this dynamically... this was a quick fix for a user that was complaining.

2023-09-19 18:12 UTC, merged