Imports & Navbar visual changes
travisdesell/ngafid2.0 pull request #151
Opened 2024-07-16 20:10 UTC by Ilverism

- Reworked how the Imports rows appear
- Modified the Uploads panel on the home page to reflect the new badges on the Imports page
- Added new icons to the Navbar
- Added a background highlight when hovering the Navbar
- Fixed the Navbar text not reflecting what the active page was for some pages

![image](https://github.com/user-attachments/assets/7b09d870-329b-41fe-b5c1-c5e702940fb1)
![image](https://github.com/user-attachments/assets/f191876e-2cc2-4aad-85a0-713b619d0e7b)

![image](https://github.com/user-attachments/assets/d9b7bee5-e5cf-45e5-bfb2-bba20c8a1ed2)
![image](https://github.com/user-attachments/assets/3fdfe9cc-449b-4433-a591-5513308948c1)

![image](https://github.com/user-attachments/assets/b8f3e596-a44c-4fc2-9aec-390efb4e89b8)
![image](https://github.com/user-attachments/assets/12247975-6891-4d72-a7a7-963794993131)

2024-08-13 13:46 UTC, jkarns275 commented
I like this

2024-08-13 13:49 UTC, jkarns275 commented on package.json
> +        "html-loader": "^5.0.0",
Reminds me that we need to keep all of our dependencies up to date... locking versions seems like a mistake?

2024-08-13 13:49 UTC, jkarns275 commented on src/main/java/org/ngafid/WebServer.java
> +        Spark.post("/protected/all_severities", new PostAllSeverities(gson));
This is also defined in your previous PR? Is your dark mode branch use this as its base?

2024-08-13 13:50 UTC, jkarns275 commented on webpack.config.js
> +    devtool: false, //"source-map",
this should not be disabled i dont think?

2024-09-03 19:39 UTC, AarC10 requested changes

2024-09-10 22:22 UTC, jkarns275 commented on src/main/java/org/ngafid/SendEmail.java
> +    //private static final String baseURL = "https://ngafidbeta.rit.edu";
Yes

2024-09-10 22:24 UTC, jkarns275 commented on webpack.config.js
> +    devtool: false, //"source-map",
This should be addressed

2024-09-10 22:25 UTC, jkarns275 commented on src/main/java/org/ngafid/SendEmail.java
> +                System.out.println("Sent messages successfully....");
real

2024-09-10 22:25 UTC, jkarns275 commented on src/main/java/org/ngafid/accounts/AirSyncFleet.java
> +        """;
People are saying multi-line strings are the way to go

2024-09-10 22:27 UTC, jkarns275 commented on src/main/java/org/ngafid/accounts/AirSyncFleet.java
> +                }
I generally prefer an else statement to a drop down. Especially in a case like this where both branches are terminal.

2024-09-10 22:27 UTC, jkarns275 commented on src/main/java/org/ngafid/accounts/AirSyncFleet.java
> +        }
This code gets deleted in a later PR so can be ignored

2024-09-10 22:28 UTC, jkarns275 commented on src/main/java/org/ngafid/accounts/AirSyncFleet.java
> +                }
Wait this is my code

2024-09-10 22:30 UTC, jkarns275 commented on src/main/java/org/ngafid/accounts/UserEmailPreferences.java
> +    private static HashMap<String, HashMap<String, Boolean>> emailTypesUsers = new HashMap<>();
Should probably just update the getters to use the `Map` interface.

2024-09-10 22:40 UTC, jkarns275 commented on src/main/java/org/ngafid/accounts/EmailType.java
> +    private final static int emailTypeNonForcedCount;
`optionalEmailTypeCount`?

2024-09-10 22:40 UTC, jkarns275 commented on src/main/java/org/ngafid/accounts/EmailType.java
> +
comment

2024-09-10 22:40 UTC, jkarns275 commented on src/main/java/org/ngafid/accounts/UserEmailPreferences.java
> +        int userID = user.getId();
Add a comment just to say this is updating the user cache maps

2024-09-10 22:46 UTC, jkarns275 commented
honestly LGTM fix conflicts and we send it

2024-09-12 17:28 UTC, AarC10 approved these changes

2024-12-17 19:32 UTC, closed without merging