Dark Mode & UI Overhauls
travisdesell/ngafid2.0 pull request #152
Opened 2024-08-12 21:53 UTC by Ilverism

**SITE-WIDE CHANGES**

- Navbar header is now sticky on all pages (will stay at the top of the screen when scrolling down; elements beneath it are simply hidden)
- Added page icons to the Navbar
- Navbar elements now have a slight background highlight when hovered
- A page's main scrollbar will now appear beneath the Navbar, rather than to the right of it (indicates the Navbar will not be scrolled)
- Forced the main scrollbar to appear on some pages where clicking certain buttons would cause the scrollbar to appear as a result, which shifts the buttons away from the user's cursor as a result
- Made the margin and spacing of high-level page elements and containers more consistent across the site
- Added a Dark Mode button toggle on the right side of the Navbar, allowing the user to switch between Light & Dark themes on any page where the Navbar is visible
- The user's theme is automatically saved and loaded across pages via localStorage
- Prevented a bright flash when loading a new page while the dark theme is enabled
- A large number of CSS changes were added to main.css to override the bootstrap styles to support the light and dark themes
- The light and dark theme colors can be easily modified or expanded on at the top of main.css by specifying the colors and 2 additional variable definitions
- Made the behavior of certain elements clearer with UI changes (e.g. moving time selection elements into one larger container)

_(Interface changes from previous commits or pages with changes that come as a result of the site-wide updates will be skipped here. May skip showing both light and dark theme comparisons for brevity. May skip changes made on previous branches.)_

**SUMMARY PAGE**

- Added badge colors to the 'Uploads' container to match the Imports page
- Added icons to for notifications and the 'Uploads' badges
- Now indicates the total number of flights imported
- Removed the divider between the graphs

![image](https://github.com/user-attachments/assets/5aa640cd-296c-4215-909c-8f715f677fd1)
![image](https://github.com/user-attachments/assets/68df6150-54f0-4c56-9105-1f38cb4e7ed4)

**EVENT STATISTICS**

- Improved dropdown button visibility

![image](https://github.com/user-attachments/assets/429d4214-1646-4c20-9379-9811db3e51de)
![image](https://github.com/user-attachments/assets/a145c22f-4771-4d8e-98d3-c0e1351f558f)

**EVENT DEFINITIONS**

- Improved table layout and readability
- Similar changes were applied to the Manage Events page, but images will be skipped

![image](https://github.com/user-attachments/assets/1f004883-2c5e-4dad-8320-fce4ee9253ba)
![image](https://github.com/user-attachments/assets/0c6ace3f-4a09-4e81-8c82-6ef7c1f03b6a)
![image](https://github.com/user-attachments/assets/673e0e65-7822-4517-a856-c39e94b64326)

**TURN TO FINAL TOOL**

- Removed unnecessary plot toggle button
- Disabled unnecessary map toggle button functionality
- Moved map to the bottom left quadrant to reflect the ordering of the Flights page
- Changed the graph and map container styling to reflect the changes to the Flights page

![image](https://github.com/user-attachments/assets/d2188a05-baa1-4b95-bee1-6279c3490065)
![image](https://github.com/user-attachments/assets/85201e8f-a381-4eee-9078-502ad903848c)

**FLIGHTS**

- Reworked the page layout
- Navbar header buttons are now evenly-sized
- The map and graph now clearly have their own distinguished containers
- The map and graph can now be easily manually expanded/collapsed when with buttons at their top left
- Condensed flight information to fit into 4 distinct boxes instead of 9
- Explicitly indicates if a flight has no recorder airports or tags, rather than just leaving the box empty
- Explicitly indicates if a flight has no events found, rather than just leaving an empty line
- Moved the button to edit a flight's tags to the container which displays the flight's tags (icon was changed from a tag to a plus to indicate that's how new tags are initially added)
- The 6 remaining buttons are evenly-sized and evenly-spaced at the end of the flight row
- The ordering of the buttons and the information displayed when clicking on them now follow the expected consistent order (tags -> events -> flight parameters -> itinerary)
- A single Paginator is used, rather than two
- The Filter, Flights, and Paginator containers are now separated from each other, rather than scrolling together

![image](https://github.com/user-attachments/assets/0827c7b6-20b2-42a2-9375-4e147af3e388)
![image](https://github.com/user-attachments/assets/3891e3bf-6783-4415-9a28-e3ab03338dd3)
![image](https://github.com/user-attachments/assets/a69ee880-d5da-4444-8686-f6f8604f7d4c)
![image](https://github.com/user-attachments/assets/2ea39030-8e4b-4e80-b7a5-ff2930f7ce94)

**IMPORTS**

- Now uses a single Paginator, instead of two
- The Paginator now appears stuck at the bottom of the page, and will stay in the same spot on the screen when scrolling
- Changed the sizing of the import rows to be more compact
- Moved the date to the same end of the row as the file name
- Added colored badges with icons
- Now indicates the total number of flights imported
- Moved the dropdown button into the import row and made it more visible

![image](https://github.com/user-attachments/assets/549cdb9f-4dcd-4a72-b4ee-e3aabd33dd2d)
![image](https://github.com/user-attachments/assets/8b6a03f4-9e66-4bc5-8ad3-3681a805b070)

**UPLOADS**

- Now uses a single Paginator, instead of two
- The Paginator now appears stuck at the bottom of the page, and will stay in the same spot on the screen when scrolling
- The Upload Flights button has been moved to the Paginator, rather than having it take up its own row
- The styling of the upload rows match the changes made to the import rows, resulting in all of the information appearing above one larger container

![image](https://github.com/user-attachments/assets/7c96d563-2c93-4154-9128-afd7e708437c)
![image](https://github.com/user-attachments/assets/8ce97c7d-f958-42bf-94fb-f89cb3d1d487)

**MANAGE FLEET**

- Moved invite button inside the top-level container
- Made the formatting of the Fleet Access Preferences and Fleet Email Preferences tables to be consistent with the containers on the Preferences page
- Capitalized the Access Level names

![image](https://github.com/user-attachments/assets/7dbcfdf7-8ab8-4385-8c65-c3274f83581e)
![image](https://github.com/user-attachments/assets/e6850e2f-4595-400d-8e92-20a4841c28d2)

2024-08-13 13:45 UTC, jkarns275 requested changes
There are a few places where tabs need to be replaced. 

In the future I think this should be broken up into smaller changes - e.g. one possible way to split this up is by changing individual pages to support dark-mode, which each would have their own PR. `6500` changes is too much to actually review in confidence.

That said I think it looks good for the most part, and most of the changes will just be visual so no catastrophic effects if there are bugs.

2024-08-13 13:45 UTC, jkarns275 commented on .gitignore
> +webpack.config.js
These should not be here

2024-08-13 13:45 UTC, jkarns275 commented on src/main/java/org/ngafid/routes/PostAllSeverities.java
> +        String eventNames = request.queryParams("eventNames");
Would making these JSON parameters simplify the code below?

2024-08-13 13:45 UTC, jkarns275 commented on src/main/resources/public/templates/welcome.html
> +        /* PREVENT FLASHBANG AFTER PAGE LOAD */
🔥

2024-08-13 13:45 UTC, jkarns275 commented on src/main/resources/public/templates/imports.html
> +    <style>
maybe this should just be part of a style sheet we load on every page so we dont have to hard-code this everywhere

2024-08-13 13:45 UTC, jkarns275 commented on src/main/resources/public/templates/event_definitions_display.html
> +    <script>
Ok same with this script - should probably not be hard-coded.

2024-08-13 13:45 UTC, jkarns275 commented on src/main/resources/public/images/clouds_dark.jpg
Where did you get this

2024-08-13 16:36 UTC, Ilverism commented on src/main/resources/public/images/clouds_dark.jpg
Found the background on Pixabay
https://pixabay.com/photos/stars-universe-space-clouds-344403/

2024-10-18 17:45 UTC, jkarns275 commented
Might just send this low key but need merge conflicts resolved

2024-12-17 19:29 UTC, merged