Proximity Fixes
travisdesell/ngafid2.0 pull request #167
Opened 2024-12-23 20:07 UTC by Ilverism

NOTE: _Separate 'temp' branch was created for this PR so that only the new changes appear. Gonna leave the original branch alone for now in case something catastrophic happens 🤷‍♂️_

**create_tables.php:**
* Flag to add update the _Rate of Closure_ table to add cascading deletes
* Aim is to prevent an error when deleting Flights with Proximity Events
* Unsure if this functionality belongs in `update_tables.php` since both use `$update_...` flags

---

**Event.java:**
* New constructor that is more suitable for the Proximity events
* Takes `startTime, endTime, startLine, endLine, severity, flightId, otherFlightId`

---

**CalculateProximity.java**

* Replaced `System` print statements with `LOG` calls
* Proximity events should now get properly attached to their respective flights; previously there were issues where, given two flights A and B with a Proximity event, the Event instances created for each respective flight would get attached to A, or one would just not get attached at all
* The lateral/vertical distances are now updated at the time when the new smallest Euclidean distance is found. Now, the Proximity Event's severity should now properly reflect `sqrt(lateral^2 + vertical^2)`

2024-12-23 21:49 UTC, AarC10 requested changes

2024-12-23 21:49 UTC, AarC10 commented on db/create_tables.php
> +        FOREIGN KEY(`event_id`) REFERENCES events(`id`) ON DELETE CASCADE   -- Source Event deleted => Delete rate of closure
You might want to update this in Josh's liquibase PR as well

2024-12-23 21:49 UTC, AarC10 commented on src/main/java/org/ngafid/proximity/CalculateProximity.java
> +
Can this line just be removed?

2024-12-23 21:49 UTC, AarC10 commented on src/main/java/org/ngafid/proximity/CalculateProximity.java
> +        double lateralDistance = Airports.calculateDistanceInFeet(flightLatitude, flightLongitude,      otherFlightLatitude, otherFlightLongitude);
Weird stuff going on with the spacing here

2024-12-23 21:49 UTC, AarC10 commented on src/main/java/org/ngafid/proximity/CalculateProximity.java
> +                LOG.info("evnets found:"  + eventsFound);
Typo

2025-01-13 18:50 UTC, jkarns275 commented on db/create_tables.php
> +        FOREIGN KEY(`event_id`) REFERENCES events(`id`) ON DELETE CASCADE   -- Source Event deleted => Delete rate of closure
True. Just keep it in mind and make a PR to that branch, you don't have to do anything to this branch.

2025-01-14 01:44 UTC, merged